cache: bundler
language: ruby
rvm:
  - 2.6.6
  - 2.7.2
  - 3.0.0
  - ruby-head

gemfile:
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile

jobs:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.5.8
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.5.8
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.5.8
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails_5.2.gemfile
